//Maya 2011 x64 Project Definition

workspace -fr "offlineEdit" "scenes/edits";
workspace -fr "scene" "scenes";
workspace -fr "movie" "data";
workspace -fr "depth" "depth";
workspace -fr "autoSave" "autosave";
workspace -fr "mayaAscii" "scenes";
workspace -fr "particles" "particles";
workspace -fr "templates" "assets";
workspace -fr "sourceImages" "source_images";
workspace -fr "mayaBinary" "scenes";
workspace -fr "images" "images";
